# ─────────────────────────────────────────────────────────────────
# MaaSakhi ASHA Alert System
# Sends real WhatsApp alerts to ASHA worker's phone
# ─────────────────────────────────────────────────────────────────

import os
from datetime import datetime
from twilio.rest import Client

# Credentials from environment variables
TWILIO_ACCOUNT_SID     = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN      = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_NUMBER = "whatsapp:+14155238886"
ASHA_WORKER_NUMBER     = os.environ.get("ASHA_NUMBER", "")

# In-memory alert storage
asha_alerts = []


def send_asha_whatsapp_alert(name, week, symptom, phone):
    """
    Sends a real WhatsApp message to the ASHA worker's phone.
    """
    try:
        client = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)

        alert_message = (
            f"🚨 HIGH RISK ALERT — MaaSakhi\n\n"
            f"Patient: {name}\n"
            f"Pregnancy Week: {week}\n"
            f"Reported: {symptom}\n"
            f"Phone: {phone}\n"
            f"Time: {datetime.now().strftime('%d %b %Y, %I:%M %p')}\n\n"
            f"⚠️ Please contact her immediately!\n"
            f"This alert was generated by MaaSakhi AI\n"
            f"based on WHO ANC 2016 danger signs."
        )

        message = client.messages.create(
            from_=TWILIO_WHATSAPP_NUMBER,
            to=ASHA_WORKER_NUMBER,
            body=alert_message
        )

        print(f"ASHA alert sent! Message SID: {message.sid}")
        return True

    except Exception as e:
        print(f"Failed to send ASHA alert: {e}")
        return False


def save_alert(name, week, symptom, phone):
    """
    Saves alert to memory AND sends real WhatsApp to ASHA worker.
    """
    alert = {
        "name": name,
        "week": week,
        "symptom": symptom,
        "phone": phone,
        "time": datetime.now().strftime("%d %b %Y, %I:%M %p"),
        "status": "Alert Sent"
    }
    asha_alerts.append(alert)

    # Print to terminal
    print(f"""
╔══════════════════════════════════════╗
  ⚠️  HIGH RISK ALERT — MaaSakhi
╠══════════════════════════════════════╣
  Patient : {name}
  Week    : {week}
  Symptom : {symptom}
  Phone   : {phone}
  Time    : {alert['time']}
╚══════════════════════════════════════╝
""")

    # Send real WhatsApp alert
    if ASHA_WORKER_NUMBER:
        send_asha_whatsapp_alert(name, week, symptom, phone)
    else:
        print("ASHA_NUMBER not set — skipping WhatsApp alert")

    return alert


def get_all_alerts():
    return asha_alerts


def get_alert_count():
    return len(asha_alerts)
